### ISSUE TITLE
Boolean type error & and error at inserting data

### ISSUE THREAD

**Issue by FrediBach** [hasura/json-data-import#1]
I've adapted my JSON GraphQL Server sample data file to work with the Hasura import and I've found two problems.

First, this is my sample file (I've removed the JSON types I had in there, to make it work): https://gist.github.com/FrediBach/53d78826f3886e6adf15f59ce530331e

First error I've got is with the yearly boolean. I fixed that by changing line 55 in src/generateTables.js:

`  if (typeof data === 'boolean') {`

After that, the script created the tables but failed with adding data:

`Creating tables...
Done!
Tracking tables...
Done!
Creating relationships...
Done!
Inserting data...
{ Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/Users/fredi.bach/Projects/hasura/json-data-import/node_modules/apollo-client/bundle.umd.js:85:32)
    at Object.error (/Users/fredi.bach/Projects/hasura/json-data-import/node_modules/apollo-client/bundle.umd.js:916:32)
    at notifySubscription (/Users/fredi.bach/Projects/hasura/json-data-import/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/fredi.bach/Projects/hasura/json-data-import/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.error (/Users/fredi.bach/Projects/hasura/json-data-import/node_modules/zen-observable/lib/Observable.js:220:7)
    at /Users/fredi.bach/Projects/hasura/json-data-import/node_modules/apollo-link-http/lib/bundle.umd.js:138:30
    at process._tickCallback (internal/process/next_tick.js:68:7)
  graphQLErrors: [],
  networkError:
   { Error: Response not successful: Received status code 400
       at throwServerError (/Users/fredi.bach/Projects/hasura/json-data-import/node_modules/apollo-link-http-common/lib/bundle.umd.js:33:21)
       at /Users/fredi.bach/Projects/hasura/json-data-import/node_modules/apollo-link-http-common/lib/bundle.umd.js:58:17
       at process._tickCallback (internal/process/next_tick.js:68:7)
     response:
      Response {
        size: 0,
        timeout: 0,
        [Symbol(Body internals)]: [Object],
        [Symbol(Response internals)]: [Object] },
     statusCode: 400,
     result: { errors: [Array] } },
  message:
   'Network error: Response not successful: Received status code 400',
  extraInfo: undefined }`

**Comment by wawhal** [comment]
Hey @FrediBach

That error is due to the problems with casing. SQL must be generated a bit differently for case sensitive names.

Fixing it. And also working on better and clearer error handling :-D

Thanks for reporting.

**Comment by FrediBach** [comment]
Ah, so the `userStatus_id` and `routeWaypoint_id` fields caused the issue.

**Comment by wawhal** [comment]
There were a couple of more issues as well. Such as handling cyclic foreign key constraints.

Its been fixed now. You can try it out.

One thing to note though. If you are setting `file_id` as a foreign key to the files table, you cannot keep it null. In case you really want to keep it null, there must be an entry in the `files` table which has data `null` and the `users` table must refer to it. For example:

```js
{
   users: [
       { id: 1, name: "Jon", file_id: 1 },
       { id: 2, name: "Mary", file_id: 2}
   ],
   files: [
       { id: 1 },
       { id: 2, uri: 'https://uploaded.file.com/' }
   ]
}
```

Hope that makes sense.

**Comment by FrediBach** [comment]
Yes, makes sense. Everything worked now. Not ideal with the file_id, but doable. Is it because relationships are always required?
